services:
  kalisi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ${KALISI_IMAGE:-kalisi/all-in-one:latest}
    environment:
      - KALISI_AUTO_START=${KALISI_AUTO_START:-false}
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS:-}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-kalisi-neo4j}
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - APPROVED_EMAILS=${APPROVED_EMAILS:-demo@example.com}
      - DOCKER_CONTAINER=true
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:2222:22"
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
      - "127.0.0.1:7681:7681"
    cap_add:
      - CAP_SETFCAP
      - CAP_NET_BIND_SERVICE
    volumes:
      - kalisi-workspace:/workspace
      - kalisi-neo4j:/data/neo4j
      - kalisi-redis:/data/redis
      - kalisi-home:/home/kalisi
      - ./source/.env:/workspace/runtime/.env:ro
    restart: unless-stopped

volumes:
  kalisi-workspace:
  kalisi-neo4j:
  kalisi-redis:
  kalisi-home:
